using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class MouseLook : MonoBehaviour
{
    
    public bool canRotation;

    public float mouseSensitivity = 100;

    public Transform body;

    float xRotation = 0f;

    // Start is called before the first frame update
    void Start()
    {
       
    }

    // Update is called once per frame
    void Update()
    {
        if(canRotation)
        {
            Cursor.lockState = CursorLockMode.Locked;
            rotation();
        }

        showMouseScreen();
    }

    void rotation()
    {
        
        float mouseX = Input.GetAxis("Mouse X") * mouseSensitivity * Time.deltaTime;
        float mouseY = Input.GetAxis("Mouse Y") * mouseSensitivity * Time.deltaTime;

        xRotation -= mouseY;
        xRotation = Mathf.Clamp(xRotation, -45f, 45f);

        transform.localRotation = Quaternion.Euler(xRotation, 0f, 0f);
        body.Rotate(Vector3.up * mouseX);
    }

     public void rotationActive(bool condition)
    {
       canRotation = condition;
    }

    public void showMouseScreen()
    {
        if(!canRotation)
        {
            Cursor.lockState = CursorLockMode.None;
        }
    }
}
